# Generated by Django 4.1 on 2022-08-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
